# .streamlit/secrets.toml

SNOWFLAKE_USER = "JPREDDY2222"
SNOWFLAKE_PASSWORD = "Nevergiveup@0207"
SNOWFLAKE_ACCOUNT = "YZJGWGY-KT25880"
SNOWFLAKE_WAREHOUSE = "FLINDERS_WH"
SNOWFLAKE_DATABASE = "STUDENTS"
SNOWFLAKE_SCHEMA = "PROJECTS"
