SNOWFLAKE_USER = "JPREDDY2222"
SNOWFLAKE_PASSWORD = "Nevergiveup@0207"
SNOWFLAKE_ACCOUNT = "YJZGWGY-KT25880.snowflakecomputing.com"
SNOWFLAKE_WAREHOUSE = "Flinders_wh"
SNOWFLAKE_DATABASE = "students"
SNOWFLAKE_SCHEMA = "projects"
